apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            memory: 1500Mi 
        volumeMounts:
        - mountPath: /usr/local/share/app
          name: app-storage1
      volumes:
      - name: app-storage1
        persistentVolumeClaim:
          claimName: app-volume-claim-x1